### ISSUE TITLE
Feature/API request: Open sheets from memory buffers

### ISSUE THREAD

**Issue by golddranks** [tafia/calamine#100]
At the moment, the `open` API seems to be the only way to open a new workbook. However, it would be good to have also a way to open sheets directly from a memory buffer, without accessing the hard disk.

Imagine that an user has uploaded a smallish XLSX file to your web service, and the backend is written with Rust. You don't want to first save the file to disk (an operation that might have a worst case latency of tens of milliseconds), and then load it there to open it up – instead, you want to directly open the file from a `&[u8]`.

**Comment by tafia** [comment]
I agree it would be more convenient.

It is not that simple though:
- I need to know the extension => we can probably have one method per file
- for xls[xmb], it needs to unzip the file. I am using `zip` crate which [requires a `Read + Seek`](https://docs.rs/zip/0.2.6/zip/read/struct.ZipArchive.html)
- I need to know before hand the size length

All of this to say that it would be probably a good idea to have a trait that is providing all this and implement that trait for `File` plus some custom struct built upon `&[u8]`.

**Comment by sanmai-NL** [comment]
@tafia: I also have this requirement. I’ll address the obstacles you mentioned:

- Expose an enum with the appropriate file formats, e.g. the existing `FileType` or some alternative, as require it as parameter to a `from_reader()` method.

- That’s not a problem with [`std::io::Cursor`](https://doc.rust-lang.org/std/io/struct.Cursor.html)
```rust
let reader = Cursor::new(bytes as &[u8]);
zip::ZipArchive::new(reader)
```

- Size length? The length of a slice is the [`len()`](https://doc.rust-lang.org/std/primitive.slice.html#method.len) method. Did you mean something more complex?

**Comment by sanmai-NL** [comment]
I implemented it, will open a PR soon. We can then discuss it there.

**Comment by tafia** [comment]
Feel free to reopen it if needed!

**Comment by ddimaria** [comment]
For anyone searching for loading an excel file from memory (a vec in this case):
```rust
let cursor = Cursor::new(file);
let mut reader: Xlsx<_> = ExcelReader::new(cursor).unwrap();
if let Ok(r) = reader.worksheet_range("Sheet1") {
    for row in r.rows() {
        println!("row={:?}, row[0]={:?}", row, row[0]);
    }
}
```
