### ISSUE TITLE
Don't clone on returning the sheet names

### ISSUE THREAD

**Issue by golddranks** [tafia/calamine#101]
The `sheet_names` method clones the vector of the sheet names. I get that this isn't likely to be on the hot path, but cloning and allocating should usually left to the user when possible. (Nothing wrong with convenience methods though). As an alternative, it would be a good practice to provide an iterator over the sheet names: `sheet_names_iter`, with `Item=&str`. This avoids both allocation and cloning, leaving the maximum flexibility in the hands of the user.

**Comment by tafia** [comment]
We could provide an additional method indeed. Do you want to make a PR?

**Comment by golddranks** [comment]
I'll send a PR during the next week!

**Comment by sanmai-NL** [comment]
@golddranks: Do you have time to pick this up again?

**Comment by tafia** [comment]
I implemented it in #111
