### ISSUE TITLE
creating nested ranges.

### ISSUE THREAD

**Issue by ZNackasha-intrepid** [tafia/calamine#117]
how can i make a range within a range . I have a complicated xlsx file that contains a lot of header and meta data. surrounding that actual data. I was wondering how I can create a nested range to focus on the actual data. 

currently I am simply using the worksheet_range function. which creates a range for the whole sheet.

**Comment by tafia** [comment]
Unfortunately it is not that easy.

The best strategy would be to iterate over your range and then build your own subranges from either several `set_value` or from the newly made public `Range::from_sparse`.
