### ISSUE TITLE
`get_value` returns incorrect value when max. index is overflown

### ISSUE THREAD

**Issue by sanmai-NL** [tafia/calamine#120]
Consider Calamine 0.14.0, and an XLSX spreadsheet with one worksheet covered by `range`.
Given `range.end() == (m_max, n_max)` where `m_max >= 0` and `n_max >= 0`,
`let a = range.get_value((m, n));` where `n == n_max + 1`,
`let b = range.get_value((m, n));` where `n == 0`, 
then `a == b`.

This is incorrect. `None` should be returned when the index of any dimension is overflown wrt. to the maximum index.

**Comment by tafia** [comment]
Thanks for the issue. Should be fixed in #121
