### ISSUE TITLE
Is it possible write excel files with this library?

### ISSUE THREAD

**Issue by madmaxio** [tafia/calamine#125]
Or some maybe somework to be done to do it?

**Comment by tafia** [comment]
No it is not possible yet sorry. Having xlsx and odd working shouldn't be too hard but definitely not trivial either. XLS and xlsb is another story.

**Comment by madmaxio** [comment]
For a rust project, what a proach would you recommend for creating custom spreadsheet?

**Comment by dertuxmalwieder** [comment]
Currently, the only library that seems to do something like that is [simple_excel_writer](https://github.com/outersky/simple_excel_writer). Is there any alternative under development?
