### ISSUE TITLE
Feature request: original order preservation for Ods::sheet_names()

### ISSUE THREAD

**Issue by kklibo** [tafia/calamine#127]
Great library, it's saved me countless hours of work. I'm using it to read ods spreadsheets, and I could use a list of sheet names in the original order that they appeared in the file.

**Comment by tafia** [comment]
Sorry for the late answer.
This is indeed a good idea. Not sure yet how it works though. I you have some time, feel free to give it a try yourself, I'd be happy to merge it. I could also help mentoring on calamine if needed.

**Comment by kklibo** [comment]
Thanks. It looks like the order is determined by the hash table it's stored in, so it's basically random now. I'll take a look this weekend.

**Comment by tafia** [comment]
We can have a `BTreeMap` if needed. The speed difference should be ridiculous.

**Comment by masklinn** [comment]
@tafia other than historical is there any reason that would not be the default everywhere? It doesn’t seem to be the case in xls files (either), and working in “the first sheet” seems pretty common, either that being the only worksheet or other worksheets being ancillary or documentation and such.

**Comment by tafia** [comment]
No there is no other reason than historical.

I didn't spend time on that particular point because I never needed it but I'd welcome any pull request.

**Comment by masklinn** [comment]
> No there is no other reason than historical.
> 
> I didn't spend time on that particular point because I never needed it but I'd welcome any pull request.

Great, I’ll find some time to do that then. Would you mind a shortcut to get a sheet by index as well?
