### ISSUE TITLE
get_value returns Empty for non-empty cells

### ISSUE THREAD

**Issue by Timmmm** [tafia/calamine#134]
If I open [this XLS](https://www.ons.gov.uk/file?uri=/peoplepopulationandcommunity/birthsdeathsandmarriages/livebirths/datasets/babynamesenglandandwalesbabynamesstatisticsboys/2016/adhocallbabynames1996to2016.xls) and try to read cell 6,2 (C7) of the sheet "Boys", it returns `Some(Empty)` when in Excel it contains the number 9. It doesn't seem to be a formula either.

Code to read it:

	let mut workbook: Xls<_> = open_workbook("names.xls").unwrap();
	let range = workbook.worksheet_range("Boys").unwrap().unwrap();
	println!("{:?}", range.get_value((6,2)));

Prints `Some(Empty)`.

**Comment by tafia** [comment]
Thanks for the issue.
I suspect this is because of the merged cells.
I'll try to have a look this week.

**Comment by tafia** [comment]
@Timmmm can you check #135. I think it will fix your issue (some record type were not supported).

**Comment by Timmmm** [comment]
Thanks! Haven't had a chance to check if it works (I actually rewrote my program to take CSV instead...) but let's assume it works. :-)
