### ISSUE TITLE
Documentation enhancement: How do I query a range of cells?

### ISSUE THREAD

**Issue by BillBarnhill** [tafia/calamine#141]
The examples I found all use the whole of sheet1 as the range. I have an Excel file that has a header row, followed by data rows grouped into sets of 4 columns each. 

For external reasons I can't use export to CSV, or change the spreadsheet in any way.

I'd like to be able to find an example in the documentation describing how to convert the string b"A2:D91" to a Range that can be used within the Serde Deserialization example, instead of getting the range via workbook.worksheet_range("Sheet1")

**Comment by tafia** [comment]
You're right this is something now too convenient at the moment (you need to build your ranges yourself)
I'll probably add a helper fn because I've had this scenario as well.
Happy to merge/review a pr if you're faster than me

**Comment by BillBarnhill** [comment]
Just getting started with Rust, and with Calamine, so not at the point yet to submit a PR. I'd really appreciate an example of building the Range for Sheet1 A2:D91, if you could. Or any example of building a cell specific Range.  This utility if I can get it working and it looks good enough to publish to the team, will be the first Rust program on our team, albeit it's a small program.

**Comment by BillBarnhill** [comment]
I have a bit of a breather now, so fell back on the old adage 'Use the Source Luke'.

Found roughly this in the comment for Range::rows, with some changes from me:
`
    use calamine::{Range, DataType};
    // ...
   // Create a range equivalent to A1:C6, with an empty data vector
    let range: Range<DataType> = Range::new((0, 0), (5, 2));
`
What I haven't found yet is how that newly instantiated Range gets tied to the data in the opened workbook so that I get that data when I map over the rows in the new Range. Continuing to look for it, but if you have a quick explanation handy, I'd appreciate it.

**Comment by BillBarnhill** [comment]
Ok, I think I've got it. Counts as my first Rust program, and the core bits are below, though it is probably not idiomatic Rust in many ways. From my tests it seems to work. This is coded for outside the crate, but if you'd like I can translate it to a PR for some added Range functions, using the cells Vec instead of get_value and set_value.

`fn copy_subrange(range : &Range<DataType>, to : &mut Range<DataType>, start: (usize,usize), end: (usize, usize) ) {
    let mut row_n = 0;
    for r in range.rows() {
        if (row_n >= start.0) && (row_n <= end.0) {
            for (i, c) in r.iter().enumerate() {
                if (i >= start.1) && (i <= end.1) {
                  //let dt = range.get_value((row_n,i)).expect("Got none for cell");
                  let dt2 = (*c).clone();
                  let to_row = (row_n as u32) - (start.0 as u32);
                  let to_col = (i as u32) - (start.1 as u32);
                  to.set_value((to_row, to_col), dt2);
                }
             }
        }
        row_n = row_n + 1;
    }
}

fn example() -> Result<(), Error> {
    let path = format!("{}/tests/lync_charge_discharge_states.xlsx", env!("CARGO_MANIFEST_DIR"));
    let mut workbook: Xlsx<_> = open_workbook(path)?;
    let range = workbook.worksheet_range("Sheet1")
        .ok_or(Error::Msg("Cannot find 'Sheet1'"))??;

    println!("Sub range A2:D5, i.e. (2,1)..(5,3)");
    dump_subrange(&range, (2,1), (5,3));
    let mut created : Range<DataType> = Range::new((0,0), (3,2));
    copy_subrange(&range, &mut created, (2,1), (5,3));
    println!("Sub range (0,0)..(3,2)");
    dump_subrange(&created, (0,0), (3,2));
    Ok(())
}`
