### ISSUE TITLE
Performance/speed

### ISSUE THREAD

**Issue by alexwennerberg** [tafia/calamine#145]
Hi! I really love the work that you did on this tool, thank you!

I've been looking for a high-performance xlsx parser that works well on large files 

I tried to parse a 270,000-row, 13-column, 21MB file and convert it to a csv, using both calamine (the sample code you provided in examples/) and the fastest xlsx library I know of, https://github.com/dilshod/xlsx2csv in python. 

xlsx2csv took 1m42s while Calamine converted this in 3m39s.

I was wondering if speed and performance is a goal of this library, and if you have any ideas for speeding things up?

**Comment by tafia** [comment]
Thanks for reaching out!

Performance is definitely something I care about. I am extremely surprised
by your numbers.

- Can you share your code / file?
- Are you sure you are compiling with `--release` flag?
- Are you doing anything else than parsing the file in the same time?

I would expect a 21m file to be well below a minute, probably less than 10s.

I was regularly working with 200mb files and it was very fast.

**Comment by alexwennerberg** [comment]
My apologies, I'm relatively new to Rust -- I was just testing using cargo run. Adding the --release flag increased the speed substantially so I'm seeing the times you mentioned. Thanks for your help!

**Comment by tafia** [comment]
No need to apologise!
Happy that you managed to get it working!
