### ISSUE TITLE
Error types don't implement std::eror::Error

### ISSUE THREAD

**Issue by theduke** [tafia/calamine#154]
Please add the respective implementations.

**Comment by tafia** [comment]
You can use the failure [compat](https://docs.rs/failure/0.1.5/failure/struct.Error.html#method.compat) fn to get an error which implements `std::error::Error`

**Comment by theduke** [comment]
@tafia  thanks!

**Comment by tafia** [comment]
You're welcome.
Just fyi, I get a timeout issue when trying to publish v0.16.0 on crates.io. I'll try later today.
