### ISSUE TITLE
Iterator over sheets

### ISSUE THREAD

**Issue by sezna** [tafia/calamine#165]
First of all, thanks for the great crate. This crate works excellently.

Currently,, there is no clean way to iterate over all of the sheets in an excel file, although it is possible to combine `sheet_names()` with `worksheet_range()`. I think it would result in a cleaner API if an iterator method was created that composes these two functions, so the consumer doesn't need to `unwrap()` after extracting the worksheet names. 

Before:
```
for sheet_name in reader.sheet_names() {
  let rows = reader.worksheet_range(sheet_name).unwrap().expect("parsing failed for sheet");
}
```

After:
```
while let Ok(sheet) in reader.sheets() {
     // work with sheet
}
```

**Comment by tafia** [comment]
Yes this could be a good addition. In the meantime this should work if you want a one line:

```rust
while let Ok(sheet) = reader.sheet_names().iter().cloned().map(reader.worksheet_range) {
    // work with sheet
}
```
