### ISSUE TITLE
How to handle errors during deserialization?

### ISSUE THREAD

**Issue by jamesmcm** [tafia/calamine#166]
Hi,

I have a struct like:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct MyRowNew {
    col1: String,
    col2: String,
    col3: String,
    col4: String,
    col5: String,
    col6: Option<f64>,
    col7: f64,
    col8: i32,
    col9: i32,
    col10: Option<f64>,
}
```

Where col10 may or may not be present in the sheet, the handling of col10 works perfectly with the code for the sheets without it:

```rust
   let iter_result = RangeDeserializerBuilder::with_headers(&[
        "col1",
        "col2",
        "col3",
        "col4",
        "col5",
        "col6",
        "col7",
        "col8",
        "col9",
    ])
    .from_range::<_, MyRowNew>(&range)?;

    for (index, row) in iter_result.enumerate() {
        println!("{}: {:?}", index, row);
    }
```

However I get errors for cases where col6 is blank or NA, ideally in both of these cases I would replace it with None:

When it is blank:
```
124: Err(Custom("Expecting f64, got \'\'"))
```

When it is NA:
```
3445: Err(CellError { err: NA, pos: (2, 0) })
```

Is there a way to handle this in the deserialisation process?

**Comment by jamesmcm** [comment]
Okay, so I "fixed" this, with this horrible pre-processing hack:

```rust
    for c in range.clone().used_cells() {
        range.set_value(
            (c.0 as u32, c.1 as u32),
            match c {
                (_, _, calamine::DataType::Error(_)) => calamine::DataType::Empty,
                (_, _, calamine::DataType::String(x)) if *x == String::from("") => {
                    calamine::DataType::Empty
                }
                x => (*x.2).clone(),
            },
        );
    }
```

Hopefully there's a better way!

**Comment by tafia** [comment]
In general when using serde, you should use a custom [`deserialize_with`](https://serde.rs/field-attrs.html#deserialize_with).

It is not straightforward but it is very flexible.

**Comment by jamesmcm** [comment]
Is there an example for doing this with the Calamine cell type?

**Comment by tafia** [comment]
I think something like this should work (I haven't tested it but it shouldn't be far from working):

```rust
use calamine::DataType;
use serde::{Deserialize, Deserializer};

fn de_opt_f64<'de, D>(deserializer: D) -> Result<Option<f64>, D::Error> {
     let data_type = DataType::deserialize(deserializer)?;
     match data_type {
         DataType::Float(f) => Ok(Some(f)),   
         DataType::Int(i) => Ok(Some(i as f64)),
         _ => Ok(None),
     }
}

#[derive(Deserialize)]
struct Row {
    #[serde(deserialize_with = "de_opt_f64")]
    col1: Option<f64>,
}
```

**Comment by jamesmcm** [comment]
Thanks, I'll try this.

It might be good to add an example to the docs too.

**Comment by tafia** [comment]
Sure, would you mind doing a PR?
Thanks! Closing the issue feel free to reopen if needed.

**Comment by jamesmcm** [comment]
Thanks, I got this to work in the end, with the following:

```rust
fn de_opt_f64<'de, D>(deserializer: D) -> Result<Option<f64>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let data_type = calamine::DataType::deserialize(deserializer);
    match data_type {
        Ok(calamine::DataType::Error(_)) => Ok(None),
        Ok(calamine::DataType::Float(f)) => Ok(Some(f)),
        Ok(calamine::DataType::Int(i)) => Ok(Some(i as f64)),
        _ => Ok(None),
    }
}
```

There are two changes compared to your pseudocode:

* We need to specify that D implements serde::Deserializer
* We cannot unwrap the Result from `calamine::DataType::deserialize(deserializer)` directly (i.e. using `?`) but instead we want to match on the `Err(_)` result there.

Thanks so much, there's no way I would have worked this out alone. I'll create a PR to add an example for the docs.

**Comment by tafia** [comment]
Awesome, thanks!
