### ISSUE TITLE
Automatic date conversion

### ISSUE THREAD

**Issue by jamesmcm** [tafia/calamine#168]
Is it possible to automatically deserialize cells to NaiveDate when the `dates` feature is enabled?

At the moment I am using:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct RawExcelRow {
    metric: String,
    #[serde(deserialize_with = "de_opt_f64")]
    value: Option<f64>,
    #[serde(deserialize_with = "de_date")]
    publish_date: chrono::NaiveDate,
    forecast_year: i32,
    forecast_week: i32,
    r#override: Option<f64>,
}


fn de_date<'de, D>(deserializer: D) -> Result<chrono::NaiveDate, D::Error>
where
    D: serde::Deserializer<'de>,
{
    let data_type = calamine::DataType::deserialize(deserializer);
    match data_type {
        Ok(x) => x.as_date().ok_or(serde::de::Error::custom("Invalid Date")),
        Err(x) => Err(x),
    }
}
```

It'd be nice if calamine could automatically apply that deserialize_with in the case that the target type is NaiveDate, NaiveDateTime, etc. (since the as_date() method is built-in when the `dates` feature is enabled).

**Comment by jamesmcm** [comment]
I had a look at this, initially I thought it would be best to add new calamine DataTypes, the problem is that:

* Excel rarely uses the date type (at least in my files), instead saving as a number type with the style set
* The style being set to a date / datetime format does not guarantee that the value is actually a valid date or datetime

In order to get the cell formats, we can read `styles.xml` in the XLSX file, and read the `CellXfs` array (the `s=N` entry for each cell will correspond to an index in this CellXfs array), then from that we can read the corresponding `numFmtId` and find that in the `NumFmts` array (this will either be `NumFmts` or inside `dxfs` with `dxf` entries).

For style numbers without an entry, their format will be according to the standard: https://docs.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.numberingformat?view=openxml-2.8.1

I started work on that, but overall given the above issues I think it would be better to ignore the formatting and just de-serialize everything to a number, and then if the target is a NaiveDate or NaiveDateTime call the existing Calamine DataType `as_date()` method.

i.e. so this code would work directly:

```rust
    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    struct RawExcelRow {
        date: chrono::NaiveDate,
    }
```

With no need for the `deserialize_with`.

I'm not sure how to do this with Serde atm since it seems we have to de-serialize according to the Serde data model and I'm not sure how to handle the chrono types there. But I think this is a much simpler solution than trying to infer which columns are dates and datetimes from the style information since it can't be distinguished from the cell type.

**Comment by tafia** [comment]
Thanks for the input. Serde doesn't know about NaiveDate so I believe it won't be possible to trigger this behavior automatically.

**Comment by jamesmcm** [comment]
It's a shame and a pain Excel doesn't clearly distinguish dates from numerics too.

I'll close this for now though and look to add the first example to the docs :slightly_smiling_face:
