### ISSUE TITLE
get value by column name

### ISSUE THREAD

**Issue by whdxwym** [tafia/calamine#170]
I read a excel with header, and want to get the value by column name. Is there a way?
`let mut workbook: Xlsx<_> = open_workbook(file_path).unwrap();
let range = workbook.worksheet_range_at(0).unwrap().unwrap();

let mut iter = RangeDeserializerBuilder::new()
.has_headers(true)
.from_range(&range)?;

if let Some(result) = iter.next() {
let row: Vec = result?;
let site = row["Site"]; //read value by column name
println!("{:?}", site);`

**Comment by tafia** [comment]
No this is not supported today.
You can get index either by relative of absolute positions (see https://docs.rs/calamine/0.16.1/calamine/struct.Range.html#method.get_value).

**Comment by tafia** [comment]
Closing for now, feel free to reopen.
