### ISSUE TITLE
Overflow when opening an xls file

### ISSUE THREAD

**Issue by genrtul** [tafia/calamine#174]
On a debug build, my program panics on overflow when trying to open an xls file. On a release build it fails with "memory allocation of 137438952448 bytes failedAborted (core dumped)". Unfortunately I can't provide the file. This is calamine version 0.16.1.
Here's my stack dump for the overflow:

thread 'main' panicked at 'attempt to subtract with overflow', /home/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/lib.rs:367:25
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/libunwind.rs:86
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:78
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1069
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1504
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:62
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:49
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:198
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:218
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:511
  11: rust_begin_unwind
             at src/libstd/panicking.rs:419
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:111
  13: core::panicking::panic
             at src/libcore/panicking.rs:54
  14: calamine::Range<T>::from_sparse
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/lib.rs:367
  15: calamine::xls::Xls<RS>::parse_workbook
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/xls.rs:286
  16: <calamine::xls::Xls<RS> as calamine::Reader>::new
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/xls.rs:144
  17: calamine::open_workbook
             at /home/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/lib.rs:214
  18: bal_convert::main
             at src/main.rs:5
  19: std::rt::lang_start::{{closure}}
             at /home/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  20: std::rt::lang_start_internal::{{closure}}
             at src/libstd/rt.rs:52
  21: std::panicking::try::do_call
             at src/libstd/panicking.rs:331
  22: std::panicking::try
             at src/libstd/panicking.rs:274
  23: std::panic::catch_unwind
             at src/libstd/panic.rs:394
  24: std::rt::lang_start_internal
             at src/libstd/rt.rs:51
  25: std::rt::lang_start
             at /home/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src/libstd/rt.rs:67
  26: main
  27: __libc_start_main
  28: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

The triggering code is just this trivial snippet:
use calamine::{open_workbook, Xls, Reader};

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let inpfile = std::env::args().skip(1).next().expect("Expected input file name");
    let mut workbook: Xls<_> = open_workbook(inpfile)?;
    Ok(())
}

**Comment by tafia** [comment]
Without the file it will be hard to check. Do you know which version of excel has generated this xls?

**Comment by genrtul** [comment]
I don't know the Excel version, and I don't know what metadata I could check to find out. The Linux "file" command identifies the file as such:
"CDFV2 Microsoft Excel"
Interestingly, if I make a copy of it with libreoffice (saving in xls format) it no longer crashes calamine and gives a different output with "file":
"Composite Document File V2 Document, Little Endian, Os: Windows, Version 1.0, Code page: -535, Revision Number: 0"

**Comment by genrtul** [comment]
Sorry, I don't really know how github works. But I managed to fix this by replacing the lines

let row_start = cells.first().unwrap().pos.0;
let row_end = cells.last().unwrap().pos.0;

in Range::from_sparse

by code that doesn't assume that the cells are sorted by row:

let row_start = cells.iter().map(|k| k.pos.0).min().unwrap();
let row_end = cells.iter().map(|k| k.pos.0).max().unwrap();

**Comment by tafia** [comment]
Thanks! I'll have a look

**Comment by happycoder97** [comment]
Hi, I'm getting a very similar error, except that it is "multiply with overflow".
<details><summary>Logs</summary>
<p>

```rust
thread '<unnamed>' panicked at 'attempt to multiply with overflow', /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/xlsx.rs:298:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/std/src/panicking.rs:475
   1: core::panicking::panic_fmt
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/30f0a07684f6c1f5df62d69e9519d82e13d6bf2d/library/core/src/panicking.rs:50
   3: calamine::xlsx::worksheet
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/xlsx.rs:298
   4: <calamine::xlsx::Xlsx<RS> as calamine::Reader>::worksheet_range::{{closure}}
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/xlsx.rs:364
   5: core::option::Option<T>::map
             at /home/farzeen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/option.rs:437
   6: <calamine::xlsx::Xlsx<RS> as calamine::Reader>::worksheet_range
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/xlsx.rs:363
   7: calamine::Reader::worksheet_range_at
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/calamine-0.16.1/src/lib.rs:203
   8: shaheen_cargo::client::upload_awb
             at ./src/client.rs:189
   9: shaheen_cargo::client::rocket_route_fn_upload_awb
             at ./src/client.rs:157
  10: core::ops::function::Fn::call
             at /home/farzeen/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ops/function.rs:72
  11: <F as rocket::handler::Handler>::handle
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.5/src/handler.rs:177
  12: rocket::rocket::Rocket::route
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.5/src/rocket.rs:296
  13: rocket::rocket::Rocket::route_and_process
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.5/src/rocket.rs:242
  14: rocket::rocket::Rocket::dispatch
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.5/src/rocket.rs:217
  15: <rocket::rocket::Rocket as hyper::server::Handler>::handle
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/rocket-0.4.5/src/rocket.rs:82
  16: hyper::server::Worker<H>::keep_alive_loop
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:340
  17: hyper::server::Worker<H>::handle_connection
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:282
  18: hyper::server::handle::{{closure}}
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/mod.rs:242
  19: hyper::server::listener::spawn_with::{{closure}}
             at /home/farzeen/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.10.16/src/server/listener.rs:50
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
</p>
</details>

My code:
```rust

    let mut awb_file = calamine::Xlsx::new(cursor).unwrap();
    let sheet = awb_file.worksheet_range_at(0).unwrap().unwrap();
```

File that caused the error:
[format (1).xlsx](https://github.com/tafia/calamine/files/5214712/format.1.xlsx)

**Comment by happycoder97** [comment]
Update:
I was using Gnumeric to edit the file.
When I opened it in LibreOffice it showed: "Could not complete reading the file because it contains more than maximum number of columns".
I then saved it to a different .xlsx file. 
Now calamine can read it :)

Updated file that no longer has the error:
[format (1).xlsx](https://github.com/tafia/calamine/files/5214750/format.1.xlsx)
