### ISSUE TITLE
[BUG] Xls::new(reader) open a excel buffer which has vba caused panic.

### ISSUE THREAD

**Issue by liangpure** [tafia/calamine#179]
```rust
let mut reader = Cursor::new(file);
let excel = Xls::new(&mut reader).unwrap();
```

panicked at "called"  Result::unwrap() on an 'Err' value: Vba(Cfb(StreamNotFound("T\u{0}h\u{0}i\u{0}s\u{0}W\u{0}o\u{0}r\u{0}k\u{0}b\u{0}o\u{0}o\u{0}k\u{0}"))).

**Comment by tafia** [comment]
Not enough context.
