### ISSUE TITLE
Handle missing columns as optional

### ISSUE THREAD

**Issue by fusillicode** [tafia/calamine#194]
Hi, first of all thanks a lot for all your incredible work 🙇 

I'm opening this issue after searching for an already baked solution and trying implementing one myself.
I hope that it may help someone having the stated requirement.

The issue pertains the need to handle missing columns as optional without raising any deserialization error.

After a few tests I found that the specific error that is returned in case of missing columns is `calamine::DeError::Custom` with an inner `String` in the form of `missing field 'COLUMN_NAME'"`.

I tried to implement a custom deserialization function to handle the case but unfortunately I hit the wall while trying to downcast a generic serde deserialization error into a concrete `calamine::DeError`.
The problem seems to be the clashing between the `'de` lifetime and the requirement of a `'static` lifetime while downcasting via `std::any::Any`.

Here's the code of the deserialization function:
```
pub fn none_if_missing_else_maybe_date_time<'de, D>(deserializer: D) -> Result<Option<NaiveDateTime>, D::Error>
where
    D: Deserializer<'de>,
{
    match calamine::DataType::deserialize(deserializer) {
        Ok(calamine::DataType::Empty) => Ok(None),
        Ok(x) => {
            match x.as_datetime() {
                None => Err(serde::de::Error::custom(format!("Invalid date {:?}", x))),
                Some(d) => Ok(Some(d)),
            }
        },
        Err(e) => {
            if let Some(de) = (&e as &dyn std::any::Any).downcast_ref::<&calamine::DeError>() {
                if let calamine::DeError::Custom(s) = &*de {
                    if s.contains("missing") {
                        return Ok(None)
                    }
                    return Err(e)
                }
                return Err(e)
            }
            Err(e)
        },
    }
}
```

Here's the compilation error I'm getting:
```
error[E0495]: cannot infer an appropriate lifetime for lifetime parameter `'de` due to conflicting requirements
   --> example/src/xlsx_models.rs:169:11
    |
169 |     match calamine::DataType::deserialize(deserializer) {
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
note: first, the lifetime cannot outlive the lifetime `'de` as defined on the function body at 165:45...
   --> example/src/xlsx_models.rs:165:45
    |
165 | pub fn none_if_missing_else_maybe_date_time<'de, D>(deserializer: D) -> Result<Option<NaiveDateTime>, D::Error>
    |                                             ^^^
note: ...so that the types are compatible
   --> example/src/xlsx_models.rs:169:11
    |
169 |     match calamine::DataType::deserialize(deserializer) {
    |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    = note: expected `Deserializer<'_>`
               found `Deserializer<'de>`
    = note: but, the lifetime must be valid for the static lifetime...
note: ...so that the type `<D as Deserializer<'_>>::Error` will meet its required lifetime bounds
   --> example/src/xlsx_models.rs:178:32
    |
178 |             if let Some(de) = (&e as &dyn std::any::Any).downcast_ref::<&calamine::DeError>() {
    |                                ^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0495`
```

Did I miss an already baked solution during my initial search? 🤔 
Is there a way to solve the over mentioned error in safe Rust and no additional crates (e.g. [downcast-rs](https://crates.io/crates/downcast-rs))?

I apologize in advance if the issue is misplaced, not clear enough or out of context to this project 🙇‍♂️

For anything do not hesitate to ask for more detail and/or clarifications.

Cheers.

**Comment by hiimnit** [comment]
I was running into the same issue - trying to handle the custom `missing field 'COLUMN_NAME'` error when using a custom deserializer.

I got my answer [here](https://stackoverflow.com/a/44303505). Turns out the solution is quite simple - just add another serde attribute `#[serde(default)]` before the first one like so:

```rust
#[derive(Serialize, Deserialize, Debug)]
struct RawExcelRow {
    #[serde(default)]
    #[serde(deserialize_with = "de_date")]
    start_date: Option<NaiveDate>,
}

fn de_date<'de, D>(deserializer: D) -> Result<Option<NaiveDate>, D::Error>
where
    D: serde::Deserializer<'de>,
{
    ...
}
```
