### ISSUE TITLE
calamine fails with bad address on a modest size xls

### ISSUE THREAD

**Issue by Kezii** [tafia/calamine#195]
To reproduce:
1) download this xls: https://jlcpcb.com/componentSearch/uploadComponentInfo
2) try to do any of the examples of calamine with it
3) observe the panic

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Cfb(Io(Os { code: 14, kind: Other, message: "Bad address" }))', src/main.rs:165:69
```

tested on Linux

**Comment by tafia** [comment]
Hey, it took me a while but I've just pushed a fix in #204 if you want to try it out.

**Comment by Kezii** [comment]
It seems to work now! Thanks

**Comment by tafia** [comment]
Great
