### ISSUE TITLE
Cannot open files with no extension

### ISSUE THREAD

**Issue by gufoe** [tafia/calamine#196]
Hello, running open_workbook_auto("filename_without_extension") will return the error:
Cannot open input file: Msg("Unknown extension")

Is there any way the library could automatically guess the file format?

**Comment by gufoe** [comment]
I know this code is probably terrible, but this is what i ended up using:

```rust
    fn open_workbook_xlsx<P: AsRef<Path>>(path: P) -> Result<Sheets, Error> {
        Ok(Sheets::Xlsx(open_workbook(&path).map_err(Error::Xlsx)?))
    }
    fn open_workbook_xls<P: AsRef<Path>>(path: P) -> Result<Sheets, Error> {
        Ok(Sheets::Xls(open_workbook(&path).map_err(Error::Xls)?))
    }
    fn open_workbook_xlsb<P: AsRef<Path>>(path: P) -> Result<Sheets, Error> {
        Ok(Sheets::Xlsb(open_workbook(&path).map_err(Error::Xlsb)?))
    }
    fn open_workbook_ods<P: AsRef<Path>>(path: P) -> Result<Sheets, Error> {
        Ok(Sheets::Ods(open_workbook(&path).map_err(Error::Ods)?))
    }
    fn open_auto<P: AsRef<Path>>(path: P) -> Result<Sheets, Error> {
        if let Ok(ret) = open_workbook_xlsx(&path) {
            Ok(ret)
        } else if let Ok(ret) = open_workbook_xls(&path) {
            Ok(ret)
        } else if let Ok(ret) = open_workbook_xlsb(&path) {
            Ok(ret)
        } else if let Ok(ret) = open_workbook_ods(&path) {
            Ok(ret)
        } else {
            Err(Error::Msg("Cannot detect file format"))
        }
    }
```

**Comment by kkirsanov** [comment]
It seems to be more aesthetic to look inside the ZIP archive and determine the extension by the presence of specific files:
/Workbook - xls
/xl/workbook.bin - xlsb
/xl/ - xlsx or xlsm

**Comment by tafia** [comment]
xls are not necessarily zipped.

@gufoe I'd be happy to merge a PR which directly updates [`open_workbook_auto`](https://github.com/tafia/calamine/blob/master/src/auto.rs#L26)

**Comment by gufoe** [comment]
@tafia I'd be glad to work on it! One question before I proceed: I could probably use a dependency to detect the file type, but I don't know if it is worth to add a dependency just for this (I'd say it's ok), but I'll let you decide, just tell me and I'll send a PR to address this issue.

Possible libraries I can test are tree_magic or mime_guess.

I am currently using the library for this project https://github.com/gufoe/csv2xlsx so it makes sense for me to contribute a bit.

**Comment by tafia** [comment]
I'd rather not have an additional dependency if possible. I don't believe this is a core feature and most people won't need it.
Thanks!
