### ISSUE TITLE
Extract Formulas - "inner" private

### ISSUE THREAD

**Issue by peschu123** [tafia/calamine#202]
Hi,
I'm not really a programmer, so this is probably an easy question. 

I want to replace(benchmark) a python script (openpyxl) to extract formulas from an excel sheet and write it into a csv file.

I started with the example on the readme page to retrieve the formulas.
This worked and I can output the formulas to stdout with other information around. But it is not clear to me how to access the "inner struct/field" to retrieve the formulas only.

I get an error that "inner" cannot be accessed directly because it's private. I played around with flat_map too, but I don't get it to work. :-( 

Would be nice, if someone can point me in the right direction, or give a simple example. :-)

Best Regards,

Peter

**Comment by tafia** [comment]
The [`worksheet_formula`](https://docs.rs/calamine/0.16.2/calamine/trait.Reader.html#tymethod.worksheet_formula) gives you a `Range` on which you should call either [`get_value`](https://docs.rs/calamine/0.16.2/calamine/struct.Range.html#method.get_value), [`get`](https://docs.rs/calamine/0.16.2/calamine/struct.Range.html#method.get) or iterate on all [`cells`](https://docs.rs/calamine/0.16.2/calamine/struct.Range.html#method.used_cells).


```rs
let formula: Range<String> = ...;
for (i, j, value) in formula.used_cells() {
    println!("row {} col {} formula: {}", i, j, value);
}
```
