### ISSUE TITLE
[FEATURE] iterate through worksheets?

### ISSUE THREAD

**Issue by Zerowalker** [tafia/calamine#205]
Currently if you want to iterate through all worksheets then you have to do something like:

`   let mut excel: Xlsx<_> = open_workbook("excel/test.xlsx").unwrap();
    let names = excel.sheet_names().to_owned();
    for name in names.iter() {
        if let Some(Ok(r)) = excel.worksheet_range(name) {
         .....
         }`

I am wondering if it's add an iterator for this directly, perhaps even returning the name at the same time,
so something like.

`   let mut excel: Xlsx<_> = open_workbook("excel/test.xlsx").unwrap();
    for (name, sheet) in excel.worksheets.iter() {
     ......
    }`

**Comment by Fuzen-py** [comment]
This seems like a common enough use case to warrant a shortcut method. I have opened a draft. Any contributions / feedback are welcome as I am new to this project.

**Comment by Fuzen-py** [comment]
Looks like this was also request in #165.
