### ISSUE TITLE
How to properly deserialize my struct?

### ISSUE THREAD

**Issue by SuperCuber** [tafia/calamine#214]
I have a struct like this:

```rust
#[derive(serde::Deserialize, serde::Serialize, Debug, PartialEq, Eq, PartialOrd, Ord, Clone)]
pub struct Song {
    pub artist: String,
    pub name: String,
    #[serde(flatten)]
    pub tags: BTreeMap<String, String>,
}
```

And the excel file has headers in the first row, can contain any number of columns in addition to the ones I explicitly specified.
How do I read it into a `Vec<Song>`? I tried the following code:
```rust
    let mut workbook: calamine::Xlsx<_> =
        calamine::open_workbook("songs.xlsx").context("read songs.xlsx")?;
    let range = workbook
        .worksheet_range("songs")
        .context("Get sheet 'songs'")??;

    let mut iter = calamine::RangeDeserializerBuilder::new();
    iter.has_headers(true);
    let iter = iter.from_range(&range)?;

    let mut res: Vec<Song> = Vec::new();
    for (rownum, record) in iter.enumerate() {
        dbg!(&record);
        let song = record.with_context(|| format!("read row {} from excel file", rownum))?;
        res.push(song);
    }
    dbg!(res);
```
But it doesn't seem to work, failing on row 0 with `field artist not found`... Am I doing something wrong? A similar piece of code worked easily with the `csv` crate.

Something I can think of is that it's because the explicitly specified columns are not in the expected order, but I want to handle that case...

**Comment by SuperCuber** [comment]
I tracked it down with simplified version of my original file, turns out the problem was that while `csv` counts an empty cell as an empty string, `calamine` counts it as a missing value.

**Comment by tafia** [comment]
Interesting. have you tried using `#[serde(default)]`, else you'll probably need to use `Option<String>` waiting for a fix.

**Comment by SuperCuber** [comment]
Yes, both of those solve the problem and it's what I went with.

**Comment by tafia** [comment]
Ok, closing it for now. Feel free to reopen if you think this is really somthing that should be addressed.
