### ISSUE TITLE
Using NOM based parsing

### ISSUE THREAD

**Issue by vivekvpandya** [tafia/calamine#218]
NOM https://docs.rs/nom/6.1.2/nom/ based parsing can increase speed significantly. I also assume that calamine uses streaming approach. Please correct me if that is wrong.

**Comment by kkirsanov** [comment]
Usually, everything is really easier and faster on parser combinators. :)
But I'm not sure that there will be time and effort to transfer all the parsing to them.

**Comment by tafia** [comment]
I personnaly won't spend time on rewriting it but I am opened to reviewing pull requests and see if this is beneficial.

**Comment by Fuzen-py** [comment]
Looked through the project to add this, I'm unsure if I sure if this is really something that would be beneficial to the project. `cfb.rs` & `vba.r`s seems to be already be a series of parsers.
