### ISSUE TITLE
Error on open_workbook for attached file

### ISSUE THREAD

**Issue by Edgeworth** [tafia/calamine#219]
The following error occurs for the file I've attached, upon trying to open it using open_workbook:

"Continued record too short while reading extended string"

This happens on calamine 0.18.0 but not 0.17.0.

[murc_2021.xls](https://github.com/tafia/calamine/files/6330387/murc_2021.xls)

**Comment by tafia** [comment]
Thanks for reporting it, I'll try to have a look but I don't have lot of time at the moment.

**Comment by Edgeworth** [comment]
Hey, no worries. I'm just using 0.17.0. It's non-urgent for me at least.

**Comment by Edgeworth** [comment]
I confirmed that this is no longer an issue, so closing this.
