### ISSUE TITLE
Error, excel files missing R Attribute

### ISSUE THREAD

**Issue by cyroalves** [tafia/calamine#261]
Calamine is returning the error `CellRAttribute`, from table files automatically-generated by Power BI.
The correct behaviour should be to address the cells in order of their apearence inside the row element.

The bug is quite easy to reproduce:

1. create a simple XLSX spreadsheet (even filling a single cell is enough)
2. unpack the XLSX file
3. open the xl/worksheets/sheet1.xml file in unpacked archive
4. delete "r" attribute from at least one <c> element
5. save changes and repack the XLSX file
6. try to read the modified file in Calamine

**Comment by forgemo** [comment]
I do have a similar issue.  I'm uncertain whether a missing r attribute is allowed or not according to the XLSX specs.

All I could find is the following information on [learn.microsoft.com](https://learn.microsoft.com/en-us/dotnet/api/documentformat.openxml.spreadsheet.cell?redirectedfrom=MSDN&view=openxml-2.8.1):

> r (Reference) | An A1 style reference to the location of this cell The possible values for this attribute are defined by the 
> ST_CellRef simple type (§18.18.7). 

It seems, however, that a missing r attribute is handled without any issues by common tools like MS Excel or LibreOffice.

As a workaround for my case, I wrote a little program that adds the missing r attributes.
After that, it's no problem to open them with calamine. 
I don't know If my program is generic enough to be applied to any kind of spreadsheet.

If you are interested in supporting missing r attributes, let me know and I will share my learnings with you.

**Comment by forgemo** [comment]
I just wanted to inform you that we (a colleague and I) decided to prepare a PR to handle missing R attributes. It will, however, take a few more days until we are confident enough with our solution.

**Comment by dimastbk** [comment]
I think we can backport fixes from https://github.com/Osmos-io/calamine/pull/4 and https://github.com/Osmos-io/calamine/pull/5. But I don't have an example file for testing.

**Comment by forgemo** [comment]
@dimastbk I'm afraid, that the fix from Osmos-io isn't sufficient. It solves only part of the problem. At least for our xlsx. We plan to hand-in a PR with with a  problem/solution description, a clean test file and our fix next week.
