### ISSUE TITLE
some string formula cells are lost

### ISSUE THREAD

**Issue by SheetJSDev** [tafia/calamine#266]
First off thanks for the shoutout in the credits!

https://github.com/SheetJS/test_files/raw/master/large_strings.xlsx the first worksheet was constructed using string concatenation.  Using the `excel_to_csv` example in the repo, the generated output is dropping all of the formula cells like

```xml
      <c r="A2" t="str">
        <f t="shared" ref="A2:Q2" si="0">CONCATENATE(A1,"a")</f>
        <v>aa</v>
      </c>

      <c r="A6" t="str">
        <f t="shared" si="1"/>
        <v>aaaaaa</v>
      </c>
```

There's a strange comment:

```
                // NB: the result of a formula may not be a numeric value (=A3&" "&A4).
                // We do try an initial parse as Float for utility, but fall back to a string
                // representation if that fails
```

Is this needed?  A formula with a numeric result will be marked with cell type `n`.  Even in the posited case where A3 is 1 and A4 is 2 and `A5=A3&" " &A4

The linked website in the comment is misleading.  It is better to reference the spec:

<img width="807" alt="ST_CellType" src="https://user-images.githubusercontent.com/6070939/181863518-fee7e270-dcd6-482b-b655-3edd8a4cd1ef.png">

The `str` cell type exclusively refers to a formula whose result is a string.  The `v` child holds the string value of the result.

**Comment by gufoe** [comment]
Is there any update on this? I also have the same problem where a concatenate formula is not interpreted and the cell is read as an empty string. I'd rather receive an error than an empty cell, if possible.
