### ISSUE TITLE
cannot read value some time at the same cell

### ISSUE THREAD

**Issue by 1991766703** [tafia/calamine#271]
```rust
pub fn test_xls() -> Result<(), Error> {
      use std::fmt::Write;
      let mut count = 0;
      let mut buffer = String::new();
      loop {
          let path = format!("{}/testfile.xls", env!("CARGO_MANIFEST_DIR"));
          let mut workbook = open_workbook_auto(path)?;
          let v = workbook.worksheets();
          let (_sheetname, range) = v.first().ok_or(Error::Msg("bad format"))?;
          let value = range.get( (0, 1) )
          .map(|s| s.to_string());
          write!(&mut buffer, "{}: {:?}\r\n", count, value).unwrap();
          count += 1;
          if count > 20 {
              break;
          }
      }
      std::fs::write("output.txt", buffer.as_bytes()).unwrap();
      Ok(())
}
```
output.txt:

0: Some("yyy_name")
1: Some("yyy_name")
2: Some("yyy_name")
3: None
4: None
5: None
6: Some("yyy_name")
7: None
8: Some("yyy_name")
9: None
10: Some("yyy_name")
11: Some("yyy_name")
12: Some("yyy_name")
13: Some("yyy_name")
14: Some("yyy_name")
15: None
16: Some("yyy_name")
17: None
18: Some("yyy_name")
19: None
20: None

[dependencies]
calamine = {git = "https://github.com/tafia/calamine.git"}

[testfile.xls](https://github.com/tafia/calamine/files/9630527/testfile.xls)

**Comment by tafia** [comment]
You are not reading from the same cell everytime.

Indeed currently, calamine use a `HashMap` to save sheet names. The default `HashMap` is cryptographically secure, which means the order will change for each run.

We should probably move to a `BTreeMap` instead so at least there is some form of ordering.

**Comment by 1991766703** [comment]
I expect to use sheet names with the original order in xls document, ie:
sheet c, sheea, sheetc in xls
I will get sheet in the order:
1 -> sheet c, 
2 ->  sheeta,
3 -> sheetc,

Btreemap is in the order by key, Vec is  in original order that i expect .
