### ISSUE TITLE
Values are the same in xls, but are different in calamine

### ISSUE THREAD

**Issue by z-Wind** [tafia/calamine#279]
[data.xls](https://github.com/tafia/calamine/files/9906735/data.xls)
```rust
fn read(path: &str, position: (u32, u32)) -> f64 {
    let mut workbook = open_workbook_auto(path).expect("Expect open file");
    let mut range = workbook
        .worksheet_range_at(0)
        .expect("NRA Layout")
        .expect("No Error");

    range.get_value(position).unwrap().get_float().unwrap()
}

let path = format!("{}/test/data.xls", env!("CARGO_MANIFEST_DIR"));
assert_eq!(read(&path, (1, 0)), 0.154171); // Pass
assert_eq!(read(&path, (0, 0)), 0.154171); // Fail
```

**Comment by fzumstein** [comment]
What you are seeing is the effect floating-point arithmetic, see: https://learn.microsoft.com/en-us/office/troubleshoot/excel/floating-point-arithmetic-inaccurate-result

Excel internally stores the currency-formatted number in `A1` as `0.15417100000000003`, whereas it stores `A2` as `0.154171`. You could compare them for equality using https://docs.rs/float-cmp/latest/float_cmp/

**Comment by z-Wind** [comment]
Thanks your kindly reply.

Does any methods to see the exact stored value?

In my computer, I see `A1` as `0.154171` in excel.

But it seems not the exact value.

![image](https://user-images.githubusercontent.com/16359142/199189843-d39e0ff8-9e71-449b-967a-3453ca98a5ac.png)

**Comment by fzumstein** [comment]
Excel doesn't give you a way to show the numbers in their raw version as stored in the file. However, you could save it as `xslx`, then unzip the file and look at the numbers under `xl/worksheets/sheet1.xml`.

It, however, looks like that value was probably not entered manually? If I overwrite `A1` with `0.154171` and save the file, I get the exact number. So most likely not connected to the formatting of `Accounting` of that cell but to how it was entered in the first place (downloaded from somewhere)?

**Comment by z-Wind** [comment]
Thanks a lot. It's really `0.15417100000000003` in the original file！！

The file I got is "2021 Primary layout spreadsheet" from [Vanguard](https://advisors.vanguard.com/tax-center#current-tax-season-information). That's why I want to know the exact value stored in the file.

Thank you for all your assistance. I really appreciate your help in resolving the problem.
