### ISSUE TITLE
[VBA] VBA written in Shift-JIS cannot be decoded correctly

### ISSUE THREAD

**Issue by k-fujino-kohei** [tafia/calamine#281]
In the case of multibyte, this code converts the binary, but it may not be appropriate for ShiftJIS.

Unfortunately, I am not very familiar with character codes.

https://github.com/tafia/calamine/blob/75bc04310e50bfac6ba9c15bdd2831447253ce2a/src/cfb.rs#L448-L457

**Comment by tafia** [comment]
I know this is a very old issue but do you have some example file?
