### ISSUE TITLE
using in wasm

### ISSUE THREAD

**Issue by caperaven** [tafia/calamine#291]
I am looking for a way to load a excel document in a web app and convert it to data.
Does calamine work with wasm?
The part that I am struggling to figure out is how I would load the file when using it in a wasm / sandbox environment.

Any assistance would be greatly appreciated.

**Comment by caperaven** [comment]
Ok, but that looks like it might work. I will certainly give it a try,
Thank you so much.
You are a star!

**Comment by tafia** [comment]
Thanks @christophe-petitjean !
