### ISSUE TITLE
Incorrect formulae of xls

### ISSUE THREAD

**Issue by ahah43** [tafia/calamine#304]
for **.xls** files, it is found that reading cells with formulae returns:

- ### **_Wrong Formula:_**

1.  Wrong addressing of all references to sheets other than the one that cell is in. 
2. The error occurs in referencing both the sheet name and the range.

- ### **_Empty Value:_**

"Empty" is returned for cells having any formula.
### Note

1. this error is not found when reading from .xlsx files processed by the exact same code (see the rust code attached below).
3. This error occurred using Calamine 0.19.1 

### Attachments

- "xlsx_formula.xlsx" and "xls_formula": Two excel files with same formulae, one is .xlsx and the other is .xls.
- main.rs: rust code shows the extraction of values and formulae from the two given excel files.
- Cargo.toml: Toml file shows the used Calamine version
- A snapshot of the program results.
- A snapshot of both values and formulae in Excel.

- ### Excel Files
[xls_formula.xls](https://github.com/tafia/calamine/files/11362881/xls_formula.xls)
[xlsx_formula.xlsx](https://github.com/tafia/calamine/files/11362882/xlsx_formula.xlsx)

- ### main.rs

```rust
use calamine::{open_workbook_auto, Reader, Rows};
use std::io::Error;
fn main() -> Result<(), Error> {
    let this_sheet = "Sheet1";
    println!("\n======================================================================\n");
    // try both xls and xlsx versions
    for excel_file in ["xls_formula.xls", "xlsx_formula.xlsx"] {
        let mut workbook = open_workbook_auto(excel_file).expect("Cannot open file");
        // extracting formulae
        println!("\nFormulae found in {:?}: {:?} are: \n", excel_file, this_sheet);
        if let Some(Ok(this_sheet_formulae)) = workbook.worksheet_formula(this_sheet) {
            let formulae_rows: Rows<String> = this_sheet_formulae.rows();
            for formula in formulae_rows.into_iter() {
                println!("\t{:?}", formula);
            }
        };
        // extracting values
        println!("\nValues found in {:?}: {:?} are: \n", excel_file, this_sheet);
        if let Some(Ok(r)) = workbook.worksheet_range(this_sheet) {
            for used_cell in r.used_cells() {
                println!(
                    "\tcolumn={:?}, row={:?}, value={:?}",
                    used_cell.0, used_cell.1, used_cell.2
                );
            }
        }
        println!("\n======================================================================\n");
    }
    Ok(())
}
```

- ### cargo.toml

```toml
[package]
name = "xls_read_issue_calamine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
calamine = "0.19.1"
```

![Screenshot 2023-05-01 045346_a](https://user-images.githubusercontent.com/5351850/235386123-ef428a1c-0955-4725-ad83-303ff03ee3fc.png)

![excel_snapShots](https://user-images.githubusercontent.com/5351850/235389114-43205a6f-f0fa-490e-b2df-dc1eb380f251.png)

**Comment by tafia** [comment]
I believe #332 fixes your issue.

**Comment by ahah43** [comment]
Perfect!
Now it works well.
Thank you for the efforts.

**Comment by ahah43** [comment]
> I believe #332 fixes your issue.

Perfect!
Now it works well.
Thank you for the efforts.
