### ISSUE TITLE
Datetime support

### ISSUE THREAD

**Issue by dimastbk** [tafia/calamine#318]
Some small (in my opinion) bugs in datetime support, that I am aware of:
* support for duration in xls/xslx/xlsb (`[hh]:mm:ss` parsed as datetime):
* * `255:10:10.as_time() == None`
* * `255:10:10.as_datetime() == datetime(1900, 1, 9, 15, 10, 10)`
* fix duration in ods, when more than 24 hours (255:10:10 => PT255H10M10S.as_time() == None), see also https://github.com/chronotope/chrono/issues/579
* support for 1904 date system in xlsb/xlsx
* ~~improve some performance https://github.com/tafia/calamine/pull/316#issuecomment-1562195694~~

**Comment by tafia** [comment]
Thanks @dimastbk for all your work on this topic, really very appreciated.
