### ISSUE TITLE
Fail to parse spreadsheet with only VBA function

### ISSUE THREAD

**Issue by lsoranco** [tafia/calamine#319]
A very simple spreadsheet with a VBA function and this code in the main rust function

```fn main() -> Result<(), Error> {
    let path = format!("{}\\Pasta1.xls", env!("CARGO_MANIFEST_DIR"));
    let mut workbook: Xls<_> = open_workbook(path)?;
    Ok(())
}
```

Is not correctly parsed, producing the result `Error: Xls(Vba(Cfb(CodePageNotFound(1033))))`

**Comment by tafia** [comment]
This codepage indeed doesn't exist. It'll be hard to debug without a file.

**Comment by lsoranco** [comment]
I am considering how would be the better way to transmit you a file. I will get back to this when I have decided that

**Comment by dimastbk** [comment]
@lsoranco can you test your file with version from #325?
