### ISSUE TITLE
special  excel name how to get value

### ISSUE THREAD

**Issue by figo361** [tafia/calamine#335]
![image](https://github.com/tafia/calamine/assets/6834921/d946c148-64af-4647-9049-8bb5fc5c34e6)
this kind of name how to get value ,in rust struct name can't have / this symbol。

**Comment by tafia** [comment]
Can you provide me with an example? (a file and a simple failing test?)
I believe it should read the proper encoding.

**Comment by figo361** [comment]
e yes ,i found a new way to get this data ,my way is define a struct to accept  excel data with its title,so i open the excel and then rename its titile name to get its data ,but i meet a new error 
![image](https://github.com/tafia/calamine/assets/6834921/375585f3-29a0-473b-96d6-3747d30e2301)
this kind of code is not success ,why This style of writing is not supported

**Comment by figo361** [comment]
![Uploading image.png…]()
this style is support! but i feel not graceful

**Comment by figo361** [comment]
![image](https://github.com/tafia/calamine/assets/6834921/162466bb-c1ff-4e32-bf46-2771b7464a16)
this style is support ,but its not graceful

**Comment by dimastbk** [comment]
What do you want do? If you want to compare cell and your values, you should use:
```rust
if Some(&DataType::String(s)) == range.get_value((0, 0)) {
    println!("123")
}
```
Not `if let`. In your last example, you copy value of cell `(0, 25)` to `title`.
```rust
let range = Range::from_sparse(vec![Cell::new((0, 0), String("A".to_string()))]);
let title = "B".to_string();
if let Some(DataType::String(title)) = range.get_value((0, 0)) {
    println!("{}", title);  // A
}
```

**Comment by figo361** [comment]
Thank you, I don't want to copy the value of title. I want to change the value of title because it has a special symbol **/**

**Comment by figo361** [comment]
oh ,sorry i means is header

**Comment by figo361** [comment]
thanks ! it work like this .
`            if Some(&DataType::String(
                "医疗器械注册人/备案人英文名称".to_string(),
            )) == range.get((0, 25))
            {
                range.set_value(
                    (0, 25),
                    DataType::String("医疗器械注册人_备案人英文名称".to_string()),
                );
            };`
