### ISSUE TITLE
Xls error: Unrecognized error: 0x3

### ISSUE THREAD

**Issue by 7Towers** [tafia/calamine#343]
When attempting to open a workbook, I'm getting the title error. 
```
Xls error: Unrecognized error: 0x3
```
<i>Edit</i>
Can someone provide me some tips to debug? ~~The sheet has some financial specifics, and customer names, so it's not easily shared. I may be able to create some dummy data, but would like to start with some tips to troubleshoot on my end, with the help of you pros~~. I was able to strip the sheet of all data, and I'm still having trouble opening it with this library. 
Sample sheet can be found [here](https://docs.google.com/spreadsheets/d/1Oc46NUkuZ_Uj5GW4bssMsFO0h3Wmn5E3/edit?usp=sharing&ouid=105796885453683062541&rtpof=true&sd=true)

The sheet is saved as an .xls. If I open the sheet in Excel and re-save as xlsx, then attempt to open the workbook in calamine, I still receive the same error. 

Nothing fancy on the opening code: 
```
    let mut workbook = match open_workbook_auto(path) {
        Ok(wb) => wb,
        Err(e) => {
            eprintln!("Error opening workbook: {}", e);
            return Err(e);
        }
    };
```
That code yields 
```
Error opening workbook: Xls error: Unrecognized error: 0x3
```

When I attempt to open these sheets using umya spreadsheets (another rust xls lib), I get a little descriptive error: 

```
ZipError: invalid Zip archive: Could not find central directory end
```
I am able to open the sheet in Excel, and with other frameworks like xlsx js (SheetJS), but that's a bit slower. 

There are many refs in this workbook to other workbooks in the same directory, as well as heavy use of macros and other content that I'm not familiar with, yet.

**Comment by dimastbk** [comment]
Hi!

> Error opening workbook: Xls error: Unrecognized error: 0x3

It seems calamine can't handle "0x03 Blank string value." in [FormulaValue](https://learn.microsoft.com/en-us/openspecs/office_file_formats/ms-xls/39a0757a-c7bb-4e85-b144-3e7837b059d7).

Could you attach a sample in GitHub? I can't download the original from Google Sheets.

**Comment by 7Towers** [comment]
Thanks @dimastbk. 

Here's the file
[Sample.xls](https://github.com/tafia/calamine/files/12182988/Sample.xls)

**Comment by 7Towers** [comment]
Update: 

Stepped through the calamine source in a fork. I triggered the error at: https://github.com/tafia/calamine/blob/3a5966f8bae69b368ddcc1c6abe01cb2166ec4c2/src/xls.rs#L1308

I can load my file if I put this hack in: 
```rs
fn parse_formula_value(r: &[u8]) -> Result<Option<DataType>, XlsError> {
    match r {
        &[0x00, .., 0xFF, 0xFF] => Ok(None), // String, value should be in next record
        &[0x01, _, b, .., 0xFF, 0xFF] => Ok(Some(DataType::Bool(b != 0))),
        &[0x02, _, e, .., 0xFF, 0xFF] => parse_err(e).map(Some),
        &[0x3, _, .., 0xFF, 0xFF] => {
            println!("Avoid 0x03 formula value");
            Ok(None)
        }, // empty
        &[e, .., 0xFF, 0xFF] => Err(XlsError::Unrecognized {
            typ: "error",
            val: e,
        }),
        _ => Ok(Some(DataType::Float(read_f64(r)))),
    }
}
```
Specifically, the

```rs
       &[0x3, _, .., 0xFF, 0xFF] => {
            println!("Avoid 0x03 formula value");
            Ok(None)
        }, // empty
```
I don't know much about xls parsing, but I see in the attached spec you referenced from MS, that the 0x03 is a blank string value, and must be ignored. 

<img width="423" alt="image" src="https://github.com/tafia/calamine/assets/109864838/cfe40459-5fa8-4390-ae31-56c03f3c46b1">


If that's the case here, perhaps safely ignoring it is logical? I'll let you confirm. If it's as simple as that, I'm happy to do a PR. Else, I'll let you advise a smarter way to handle it.

**Comment by tafia** [comment]
Seems like a fix to me. Please open a PR. Thanks

**Comment by jqnatividad** [comment]
@7Towers  I can't reproduce this error with master using your sample file.

Is this still an issue?

**Comment by 7Towers** [comment]
Made a PR for this: #348
