### ISSUE TITLE
xls error: Zip(InvalidArchive("Could not find central directory end"))'

### ISSUE THREAD

**Issue by Xiaobaishushu25** [tafia/calamine#366]
when i try to use  open_workbook function to read a xls file,it report error:thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Zip(InvalidArchive("Could not find central directory end"))', src\main.rs:30:106, i also try to read a xls file with small amounts of data in the same folder，it success.
I can use Excel to open it normally. Is it because there are too many rows of data? (about 12000 row).

**Comment by dimastbk** [comment]
Xls is a binary format that does not use zip. Maybe you are trying to open an xlsx file with the annotation "Xls"?

**Comment by Xiaobaishushu25** [comment]
> Xls is a binary format that does not use zip. Maybe you are trying to open an xlsx file with the annotation "Xls"?

I'm also curious why zip is involved.The initial extension of the file is "xls",and can use Excel to open it normally, but if i chage the extension to xlsx, the excel will alert "Excel cannot open the file 'xx.xlsx' because the file format or file extension is invalid. Please ensure that the file is not damaged and that the file extension matches the format of the file". And both of them use calamine to read report the same error:
```
thread 'main' panicked at 'called Result::unwrap() on an Err value: Zip(InvalidArchive("Could not find central directory end"))',
```

**Comment by tafia** [comment]
Awesome, there is also the [open_workbook_auto][1] function in case you want calamine to infer the workbook type from the file extension.

[1]: https://docs.rs/calamine/latest/calamine/fn.open_workbook_auto.html
