### ISSUE TITLE
Please add `worksheet_range_ref` for `calamine::Xls` and `calamine::Ods`

### ISSUE THREAD

**Issue by lucatrv** [tafia/calamine#383]
As in subject, release 0.23.0 added `worksheet_range_ref` for `calamine::Xlsx` but not for `calamine::Xls` and `calamine::Ods`.

**Comment by dimastbk** [comment]
Xls/Ods don't support lazy iteration, see https://github.com/tafia/calamine/pull/370#issuecomment-1789074220

**Comment by lucatrv** [comment]
Thanks for the info, I didn't know. Maybe I should keep this issue open because it would be useful to document this, for instance [here](https://docs.rs/calamine/latest/calamine/struct.Xlsx.html#method.worksheet_range_ref).
