### ISSUE TITLE
Feature Request: please add method `RangeDeserializerBuilder::with_headers_struct`

### ISSUE THREAD

**Issue by lucatrv** [tafia/calamine#395]
Often we need to write something like:

```rust
#[derive(Deserialize, Serialize)]
struct Record {
    #[serde(rename = "Property")]
    house: &'static str,
    #[serde(rename = "Price")]
    value: f64,
}

let iter_results =
    calamine::RangeDeserializerBuilder::with_headers(&["Property", "Price"]).from_range(&range)?;
```

However, for structs which derive `Deserialize`, it is possible to get the Serde field names from the struct type, see for instance the [`serde_aux::serde_introspection`](https://docs.rs/serde-aux/latest/serde_aux/serde_introspection/index.html) and [`rust_xlsxwriter::deserialize_headers`](https://docs.rs/rust_xlsxwriter/latest/rust_xlsxwriter/struct.Worksheet.html#method.deserialize_headers) implementations.

It would be very convenient to add a `RangeDeserializerBuilder::with_headers_struct` (or other name) in order to write:

```rust
#[derive(Deserialize, Serialize)]
struct Record {
    #[serde(rename = "Property")]
    house: &'static str,
    #[serde(rename = "Price")]
    value: f64,
}

let iter_results =
    calamine::RangeDeserializerBuilder::with_headers_struct::<Record>().from_range(&range)?;
```

@tafia if you agree I can implement this and issue a PR.

**Comment by tafia** [comment]
Sure!
Why not directly something like `from_range_with_header<T>`?

**Comment by lucatrv** [comment]
> Why not directly something like `from_range_with_header<T>`?

I though it would be better to keep aligned with `RangeDeserializerBuilder::with_headers` and possible other future methods `RangeDeserializerBuilder::with_columns` and `Range::rows_with_columns`, as discussed with feature request #314. They all specify the elements to keep, while the range is specified elsewhere.
However I'm also good with `from_range_with_headers::<T>(&range)` if you prefer it, but then maybe there could also be a `from_range_with_headers_slice(&range, &headers)`.

**Comment by lucatrv** [comment]
After thinking a little bit more about this, IMHO the best choice is `RangeDeserializerBuilder::with_deserialize_headers`.
