### ISSUE TITLE
Find a new name

### ISSUE THREAD

**Issue by tafia** [tafia/calamine#41]
As per [reddit thread](https://www.reddit.com/r/rust/comments/5brn9f/introducing_office_a_pure_rust_reader_for_excel/) the name is really not good. 

@brunoqc do you have any idea for the new name?
I'll settle tomorrow (the sooner the better but I need some time to decide).

Some research on the excel verb:
http://www.merriam-webster.com/thesaurus/excel

Some other candidates
1.  xlrs (eXceLRuSt)
2. excellent / excel-lent (weird meaning in french as it is not necessarily slow)
3. exceller (there is a wikipedia page about a "exceller" horse, I like the image https://en.wikipedia.org/wiki/Exceller)
4. xlsr: variant of 1. but starting with "xls" like excel files
5. excel-reader

I tend to like 1. the most

Proposed by reddit users:
- Excellerator (killercup)

**Comment by Phrohdoh** [comment]
FWIW I came up with `excellerator` in my head before I finished reading the candidate list.
That or `xlrs` is 👍 IMO.

**Comment by ivanceras** [comment]
Rivets - something use to mount sheet metals together.
Also galvan from galvanized iron

**Comment by tafia** [comment]
I like rivets!

**Comment by serprex** [comment]
Prefer excellerator or xlsr. Why not xls?

**Comment by tafia** [comment]
Thanks for your comment. xls is indeed an option, I'm afraid it is used somewhere (couldn't find any example though)

**Comment by serprex** [comment]
The only place that matters is https://crates.io/crates/xls

**Comment by Phrohdoh** [comment]
I highly advise against `xls` with the main argument being that this crated _doesn't support_ the binary xls format.

**Comment by tafia** [comment]
This is true indeed

**Comment by tafia** [comment]
Well it does (at least with a high enough biff) the example is just not up to date. There is a running xls test in the tests/tests.rs

**Comment by Havvy** [comment]
Why not just `excel_file_reader`? It's boringly obvious as to what it does. Remembering puns across languages gets hard...

**Comment by tafia** [comment]
I think ironically that you remember it less with long names (always mess some part), but this is very personal. 

For discoverability I rely on crates.io ... 

But I'm very ready to be convinced otherwise

**Comment by Phrohdoh** [comment]
@Havvy Makes a fair point that the name should definitely include `excel`.
I would definitely search crates.io for `excel` if I were after a crate like this.

**Comment by Saiyt** [comment]
I like Rivets or Sheet Metal

**Comment by brianp** [comment]
If you go with Rivets make it Rivets-rs as Rivets is an existing js project.

**Comment by jsquires** [comment]
If you still want to keep the project open to eventually working with other MS office formats, how about `secretary`?

**Comment by ivanceras** [comment]
rosie from "Rosie, the riveter"
riveters - rivete-rs, logo: r}ivet{s
galvanize-rs
or
schrute - from  Dwight scrute in "The office"

**Comment by UtherII** [comment]
Or maybe rs-office as a reference to ms-office

**Comment by rustafaria** [comment]
What about "excel" or "xlsx"? Does the crate name need to be a pun or use "rs"?

**Comment by cramertj** [comment]
Just to contribute to the bikeshed, I'd like to +1 the crate name "excel" and the github name 'excel-rs". It makes it obvious what it is/what it does.

**Comment by ivanceras** [comment]
What if somebody submits a PR to support opendocument format (.ods) used in libreoffice. Certainly it's not just excel anymore. The name should be something that pertains to spreadsheets, workbook, worksheets.

**Comment by rustafaria** [comment]
@ivanceras sheet / sheet-rs ?

**Comment by Phrohdoh** [comment]
@ivanceras: Not if @tafia doesn't plan on taking the project in that direction.

**Comment by tafia** [comment]
Thank you all for your comments!! I am very happy to see people willing to brainstorm on it.

I really don't want to be offensive, rude, diminish your participation or whatever but I couldn't find a single name out of your propositions.

Let me explain:

- **excel**:  I prefer avoiding excel in the name for two main reasons: 
  - I don't want people to assume there is any link with Microsoft. I'd prefer avoiding brands as much as possible (not to repeat the mistake with the current name). I will rely on tags in crates.io for people searching for an excel reader 
  - As @ivanceras mentioned, while I have no immediate plan of implementing other format (there is still a lot to do to refine excel support), I'd like to keep the door opened, either for me or for any contributor
  - discards excel, excellerator, excel-reader, excel_file_reader,
- **xls, xlsr, xlrs, xlsx**: 
  - xls is probably the best choice here, as it looks more generic. It took me some time to understand that js-xlsx implemented all excel files. I suppose the name was picked when the development focus was on xlsx files (simplest to implement as you don't need the specs to start)
  - on the other hand, as for the previous point, it is too close to excel (it would be fantastic to have a odt support someday)
- **rivets, riveters, rivet-rs**: I like rivets a lot but as @brianp mentioned there is a fairly big js project with that name and it will probably be confusing. As for riveters, it "sounds" not nice to me (I'm not English speaker so I may have the accent wrong in my head)
- **rs-office**: I like this but I want to restrict the scope to sheets processing for the moment.
- **sheets, sheet-rs**: This is too close to sheetjs IMO, and while I confess having cheated a lot with their code I have no direct relation with them. Would they want to have their own rust implementation, I feel like they deserve that name more than me
- **secretary**: I like this one, but as for office or rs-office, this has a too broad meaning
- **rosie, schrute**: I am not familiar with those ...
- **galvan**: I love the link between sheets and rust .... but it *prevents* rust!

... no I have no more candidates! I am probably too strict but 

I have a new contender. Looking at the [french wikipedia page](https://fr.wikipedia.org/wiki/Galvanisation) for galvanization (which is strangely much more detailed than the english version), I found that **calamine** prevents galvanization! 
I like this name as it reminds me my childhood and, like galvan, as a link between sheets and rust. 

Except if someone really dislikes it, I will probably pick on this one.

**Comment by tafia** [comment]
Thanks everyone for your time! [calamine](https://crates.io/crates/calamine) crate has now been published. :tada: 
I don't feel really well about the totalitarian naming but I hope you'll understand my reasons.
