### ISSUE TITLE
Is there a way to get the "original value" of a cell that has an Error?

### ISSUE THREAD

**Issue by jqnatividad** [tafia/calamine#416]
For example, if there is a Div by Zero error in a cell, can I get the formula text (e.g. "=100/0") instead of "#DIV/0!"?

**Comment by tafia** [comment]
You can get the formula separately.
There is no "simple" way to connect the 2 for now
https://docs.rs/calamine/latest/calamine/enum.Sheets.html#method.worksheet_formula

**Comment by jqnatividad** [comment]
Thanks @tafia !  Just needed to be pointed in the right direction...

**Comment by jqnatividad** [comment]
I implemented  retrieving the formula text per your suggestion to use `worksheet_formula` in combination with `get_value`.

And it works!

But interestingly, only on macOS, and not on Windows or Linux (or more specifically, the Windows and Linux Github Action Runners")

Very strange...  any thoughts why it works on macOS but not other platforms?

GH Action runner on Linux:
https://github.com/jqnatividad/qsv/actions/runs/8563583350/job/23468826400

On macOS:
https://github.com/jqnatividad/qsv/actions/runs/8563583347/job/23468826402

**Comment by jqnatividad** [comment]
Closing this as it seems the problem is with GitHub's action runners.

When I run the tests locally on native hardware, they work as expected. It may be an issue with GH runners running on Azure VMs.
