### ISSUE TITLE
memory allocation error when reading xls files with merged regions

### ISSUE THREAD

**Issue by bwkam** [tafia/calamine#444]
Hello, I was trying out the new merged regions commits recently, it all works perfectly fine except for XLS files. I'm not sure why. I've managed to create a minimal reproducible sample of the bug. When I run it, it panics with:
```
2024-06-24T11:19:14.794480Z DEBUG calamine::cfb: load minis    
memory allocation of 2199023255552 bytes failed
```

This is the sample: https://github.com/bwkam/calamine-bug-sample
I checked, and this is also reproducible with v0.25.

Edit: I tried with another XLS file, and it worked fine. I don't know what's wrong with this one. Perhaps its something with the XLSX to XLS converter I used.

Thanks.

**Comment by tafia** [comment]
Hey, sorry for the late response. I can't access the link, do you mind uploading it again?

**Comment by bwkam** [comment]
Sorry, forgot it was private. Should work now

**Comment by tafia** [comment]
Ok I can reproduce. It's late where I live I'll try to have a look ASAP.

**Comment by tafia** [comment]
Sorry it took me longer than expected to get some time. Should be fixed now.
