### ISSUE TITLE
bump quick-xml dependency

### ISSUE THREAD

**Issue by jqnatividad** [tafia/calamine#454]
Since quick-xml 0.31 was released late 2023, there have been six releases, all within the last two months.

https://crates.io/crates/quick-xml/versions

calamine only compiles to 0.31.0 as there are breaking API changes 0.32 and above.

Are there any benefits that calamine can benefit from in later release of quick-xml?

cc @mingun

**Comment by tafia** [comment]
No there is no particular reason but the lack of time to check what the changes are.
