### ISSUE TITLE
Loading sheets with different locale depends on sheet name

### ISSUE THREAD

**Issue by dbkup** [tafia/calamine#64]
As an intro into Rust, I set a task for myself to convert some Excel files into JSON. My Excel files only have one sheet, they're basically csvs with numbers and strings, 

I run into the issue that I need to enter the sheet name to open it i.e. `workbook.worksheet_range("Sheet1")`. When I tried running the code above I got an error `"Sheet \'Sheet1\' does not exist"'`. I opened the Excel to confirm it had the sheet, and realized the name was `"Tabelle1"` as it's created with the German locale. I realized that the actual user defined sheet name has to be used for `workbook.worksheet_range()` if I understand the code in `read_sheets_names()` correctly. 
I was hoping to find out more and dug through the calamine code to figure out if there is another option. I didn't find any other way to reference the sheets. This feels like a good point for an enhancement request. The good thing is that `workbook.worksheet_range("Tabelle1")` opens the file correctly and I get the data.

After unzipping the excel file, I believe a solution might be something like:
The opened `workbook.xml` has a `sheetId` property and the actual sheet xml name still stays `sheet1.xml` in my case. I'm not sure if there are differences between the format revisions. I only tested on Excel2010. So I'm guessing that the path or the `sheetId` can be used for another reference. For instance when fetching sheets by name in `read_sheets_names()` we add the `sheetId` of the sheet to the resulting `sheets` object. Then a new function could take advantage of this and get the sheet by passing in it's number, i.e. "1".

That's my suggestion, I'd submit a pull request, as I said this is my first attempt at using rust, so I'll leave it at the suggestion level.
Thanks for the work on the wrapper, it's way over my head, but feels good to read the code and try and understand it 😃. Happy new year!

**Comment by tafia** [comment]
Thanks for opening the issue.

The actual name in the xml is a technical detail as there is no such name in `xlsb` files for instance. 
As for a c# library, we don't expect `Sheet1` to return the *first* sheet but the sheet with that exact name.

To address your issue, we could probably try implementing `Index` trait and return the sheets in the order they appear in the file.
If you want to give it a try, we may need to change [this function](https://github.com/tafia/calamine/blob/master/src/xlsx.rs#L85-L112) to return a collection which preserves the order (a `Vec<(_, _)>` should be good enough as we are not expecting many sheets per file).

Let me know if you don't feel comfortable or you don't have the time, I can happily do it myself.

**Comment by dbkup** [comment]
Thanks for the quick reply and fix 👍 Sorry for the late response. It would have taken me some time to get to a good implementation, as a total beginner with Rust. I will give the new feature a run once the regular job stuff quiets down.

**Comment by tafia** [comment]
No worries !
Let me know once you find the time
