### ISSUE TITLE
lifetime issue when itering over the `sheet_names()`

### ISSUE THREAD

**Issue by grissiom** [tafia/calamine#69]
Here is the code:
``` rust
    let mut xl = Excel::open(&sce).unwrap();
    for stn in xl.sheet_names().unwrap() {
        let range = xl.worksheet_range(stn).unwrap();
        write_range(&mut dest, range).unwrap();
    }
```
I want to iter over the sheets with sheet names. But when I compile it, I got lifetime issue:

```
error[E0499]: cannot borrow `xl` as mutable more than once at a time
  --> src/main.rs:28:21
   |
27 |     for stn in xl.sheet_names().unwrap() {
   |                -- first mutable borrow occurs here
28 |         let range = xl.worksheet_range(stn).unwrap();
   |                     ^^ second mutable borrow occurs here
29 |         write_range(&mut dest, range).unwrap();
30 |     }
   |     - first borrow ends here

error: aborting due to previous error
```

Is there any way to fix it easily?

**Comment by tafia** [comment]
Sorry I forgot to answer you.
The easiest way is just to own the sheet names (this is cheap anyway).
```rust
    let mut xl = Excel::open(&sce).unwrap();
    let sheet_names = xl.sheet_names().map(|s| s.to_string()).collect::<Vec<_>>();
    for stn in &sheet_names {
        let range = xl.worksheet_range(stn).unwrap();
        write_range(&mut dest, range).unwrap();
    }
```

An alternative is to use the `worksheet_range_by_index` but then you need to know the upper bound.
I agree this is not ideal and we could probably have something simpler (like an iterator over all `sheet_range`s ?).

I don't have much time now but I could probably do it next week or so. Eventually if you want to give it a try I'll be more than happy to merge!

**Comment by grissiom** [comment]
I opened a PR on this. But I'm new to Rust, so please review it hardly. Thank you very much! ;-)
