### ISSUE TITLE
OpenOffce Support

### ISSUE THREAD

**Issue by kawasakitoshiya** [tafia/calamine#75]
I hope you support `.ods` :)

**Comment by tafia** [comment]
Yes this would be great indeed! I do not have time at the moment but this is definitely on my to-do list!

**Comment by kawasakitoshiya** [comment]
@tafia Thank you for your quick work!

i'm on the trip this week, so i'll try next week 😉

**Comment by tafia** [comment]
No pb! I've just added defined named as well and refactored some internals.
