### ISSUE TITLE
Bug in sheet name parsing

### ISSUE THREAD

**Issue by ramn** [tafia/calamine#80]
See failing test: https://github.com/ramn/calamine/tree/failing_test_for_sheet_name_parsing

**Comment by tafia** [comment]
Thanks for the isssue. Do you know how this particular file has been created?

When I try to save it under a new name using MsExcel 2010, the file changes significantly (becomes much bigger) and test passes.

**Comment by tafia** [comment]
Forget about this. I fixed the bug in #81.
Thanks!

**Comment by tafia** [comment]
Published v0.10.2

**Comment by ramn** [comment]
Don't know how it is created.

Thanks for the fix, works for me!

**Comment by tafia** [comment]
>Don't know how it is created.

I've checked the BIFF version, it is decently recent so it didn't really matter in fact. The bug was really that I didn't treat singlebyte encodings properly.
