### ISSUE TITLE
Expose typed data for dates and times

### ISSUE THREAD

**Issue by jrmuizel** [tafia/calamine#95]
Currently they're just strings it would be nice if we could add support for exposing the type of these cells.

**Comment by tafia** [comment]
Yes you're right. I have to dig into the documentation to parse this properly but I do not have much time at the moment, perhaps you'd like to give it a try?

**Comment by yivo** [comment]
@tafia I am getting float value when trying to parse date-types cell.

I have included the example xlsx: 
[book.xlsx](https://github.com/tafia/calamine/files/1362871/book.xlsx)

**Comment by dkkoval** [comment]
@tafia this functions from [xlsx-js](https://github.com/SheetJS/js-xlsx) might be useful:

* [`parse_date_code`](https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L204)
* [`write_date`](https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L290)
* [`fmt_is_date`](https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L654)
* [`read_date`](https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L1345)
* [`parseDate`](https://github.com/SheetJS/js-xlsx/blob/master/xlsx.js#L1795)

Maybe just implement that in rust?

**Comment by tafia** [comment]
Thanks!
I'm a little busy at the moment, I'll try to make it as fast as possible. Feel free to make a PR!

**Comment by tafia** [comment]
> I can give it a try if you don't mind 😜

I am starting to look at it but this is far from trivial. I really don't mind if you look at it 😄 .

Instead of having a `calamine::DateTime` struct, I'd prefer, if possible having some existing item:
- either `std::time::Instant` 
- or `chrono::DateTime` (not sure if it is overkill or not)?

What do you think?

**Comment by dkkoval** [comment]
I'd prefer unix timestamp (`i64`), cause it can be used in any time/date lib (e.g. [chrono](https://docs.rs/chrono/0.4.0/chrono/offset/trait.TimeZone.html#method.timestamp)).

**Comment by tafia** [comment]
Looks good to me too!

**Comment by nimtiazm** [comment]
Hi,
Has anyone worked on this ticket? If not completely, can you share what you've figured out so far? I mean what exactly needs to be done to be able to parse date/time columns?

**Comment by tafia** [comment]
I had a look and having a perfect solution is not simple. Basically we need to parse the text format and decide upon it.

You can always have a look at https://github.com/SheetJS/js-xlsx implementation. It is not easy to read and I am not sure there is a one fits all solution (xlsb and xlsx will likely be different).

**Comment by robyoung** [comment]
Is there anything left to do before this issue can be closed?
