### ISSUE TITLE
Serde serialization and deserialization?

### ISSUE THREAD

**Issue by erickt** [tafia/calamine#96]
Hello!

Have you considered adding support for [serde](https://serde.rs) support for serialization and deserialization, at least for the `DataType` type? It seems like it would be pretty straightforward. Are there any downsides to doing this that I'm not thinking of?

**Comment by tafia** [comment]
I'd love adding serde support. 

Unfortunately it doesn't look that trivial to me, for instance, I am deserializing several different file format into `DataType`, wouldn't this be an issue?

I haven't looked at it yet to be honest.

**Comment by tafia** [comment]
Closing as the serialization part needs calamine to be able to write an excel file.
Thanks again @erickt
